//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_price
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string LangCode { get; set; }
        public Nullable<int> Price_min { get; set; }
        public Nullable<int> Price_max { get; set; }
        public Nullable<int> Ordering { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    }
}
