//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_publisher
    {
        public int ID { get; set; }
        public int ParentID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public string LangCode { get; set; }
        public string KyHieu { get; set; }
        public string MaSo { get; set; }
        public Nullable<long> TKNganHang { get; set; }
        public string TenNganHang { get; set; }
        public Nullable<int> Ordering { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    }
}
