//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_eMagazine
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Photo { get; set; }
        public string Author { get; set; }
        public Nullable<int> CTVID { get; set; }
        public Nullable<int> NewMoney { get; set; }
        public Nullable<int> Width { get; set; }
        public string Background { get; set; }
        public bool Status { get; set; }
        public string Source { get; set; }
        public string Info { get; set; }
        public int Ordering { get; set; }
        public string Color { get; set; }
    }
}
