//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubeMagazine
    {
        public int ID { get; set; }
        public Nullable<int> IDParent { get; set; }
        public int Ordering { get; set; }
        public string StrPhoto { get; set; }
        public int NumberPhoto { get; set; }
        public bool isFullWidth { get; set; }
        public Nullable<int> WidthPhoto { get; set; }
        public Nullable<int> PositionPhoto { get; set; }
        public string Content { get; set; }
    }
}
