//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_NEWS_LISTDATA
    {
        public Nullable<int> CreatedBy { get; set; }
        public int CategoryId { get; set; }
        public string NguoiTao { get; set; }
        public int ID { get; set; }
        public string TieuDeChinh { get; set; }
        public Nullable<int> Status { get; set; }
        public string AnhDaiDien { get; set; }
        public string LangCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Author { get; set; }
        public string CatName { get; set; }
        public string CatImage { get; set; }
        public string CatImage2 { get; set; }
        public string Description { get; set; }
        public Nullable<byte> IsGetNews { get; set; }
        public Nullable<byte> AllowComment { get; set; }
        public Nullable<long> ViewCount { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public string Tags { get; set; }
        public Nullable<int> NewMoney { get; set; }
        public string MainTitle { get; set; }
        public string Avatar { get; set; }
    }
}
