//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Images_ImageCategory
    {
        public string Title { get; set; }
        public string Images { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public bool Status { get; set; }
        public Nullable<int> Ordering { get; set; }
        public string CateName { get; set; }
        public string ImageCategoryId { get; set; }
    }
}
