//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Images
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Images { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public bool Status { get; set; }
        public int ImageCategoryId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LangCode { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
        public int Ordering { get; set; }
        public int UserActId { get; set; }
        public int ProcedureId { get; set; }
    }
}
