//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qProcess
    {
        public int Id { get; set; }
        public string TableCode { get; set; }
        public int FKId { get; set; }
        public int FromProcedure { get; set; }
        public int FromId { get; set; }
        public int ToId { get; set; }
        public int ToProcedure { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Attachment { get; set; }
        public string LangCode { get; set; }
    }
}
