//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Topic
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Photo { get; set; }
        public string Details { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Author { get; set; }
        public string LangCode { get; set; }
        public string Tags { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<long> ViewCount { get; set; }
        public Nullable<byte> AllowComment { get; set; }
        public string Attachment { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string ListImgSlide { get; set; }
        public string IdNguoiChon { get; set; }
    }
}
