//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Chat
    {
        public int ID { get; set; }
        public string ListIdUser { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Count { get; set; }
        public Nullable<int> IdLast { get; set; }
        public string LangCode { get; set; }
        public Nullable<int> Ordering { get; set; }
    }
}
